/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as UsageRouteImport } from './routes/usage'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PairRouteImport } from './routes/pair'
import { Route as MailRouteImport } from './routes/mail'
import { Route as HomeRouteImport } from './routes/home'
import { Route as DriveRouteImport } from './routes/drive'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as ChatRouteImport } from './routes/_chat'
import { Route as HomeIndexRouteImport } from './routes/home.index'
import { Route as ChatIndexRouteImport } from './routes/_chat.index'
import { Route as SettingsStorageRouteImport } from './routes/settings.storage'
import { Route as SettingsSourceControlRouteImport } from './routes/settings.source-control'
import { Route as SettingsSnapShotRouteImport } from './routes/settings.snap-shot'
import { Route as SettingsScheduledTasksRouteImport } from './routes/settings.scheduled-tasks'
import { Route as SettingsProvidersRouteImport } from './routes/settings.providers'
import { Route as SettingsProjectsRouteImport } from './routes/settings.projects'
import { Route as SettingsProjectGroupsRouteImport } from './routes/settings.project-groups'
import { Route as SettingsOpenSourceLicensesRouteImport } from './routes/settings.open-source-licenses'
import { Route as SettingsKeybindingsRouteImport } from './routes/settings.keybindings'
import { Route as SettingsIntegrationsRouteImport } from './routes/settings.integrations'
import { Route as SettingsGeneralRouteImport } from './routes/settings.general'
import { Route as SettingsExtensionsRouteImport } from './routes/settings.extensions'
import { Route as SettingsDiagnosticsRouteImport } from './routes/settings.diagnostics'
import { Route as SettingsConnectionsRouteImport } from './routes/settings.connections'
import { Route as SettingsCodeIntelligenceRouteImport } from './routes/settings.code-intelligence'
import { Route as SettingsArchivedRouteImport } from './routes/settings.archived'
import { Route as SettingsAppearanceRouteImport } from './routes/settings.appearance'
import { Route as ProjectsProjectKeyRouteImport } from './routes/projects.$projectKey'
import { Route as HomeNeedsYouRouteImport } from './routes/home.needs-you'
import { Route as HomeAgentsRouteImport } from './routes/home.agents'
import { Route as AccountSignOutRouteImport } from './routes/account.sign-out'
import { Route as AccountCallbackRouteImport } from './routes/account.callback'
import { Route as ChatPullRequestsRouteImport } from './routes/_chat.pull-requests'
import { Route as HomeViewsViewIdRouteImport } from './routes/home.views.$viewId'
import { Route as HomeProjectsProjectIdRouteImport } from './routes/home.projects.$projectId'
import { Route as ChatDraftDraftIdRouteImport } from './routes/_chat.draft.$draftId'
import { Route as ChatEnvironmentIdThreadIdRouteImport } from './routes/_chat.$environmentId.$threadId'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const UsageRoute = UsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PairRoute = PairRouteImport.update({
  id: '/pair',
  path: '/pair',
  getParentRoute: () => rootRouteImport,
} as any)
const MailRoute = MailRouteImport.update({
  id: '/mail',
  path: '/mail',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const DriveRoute = DriveRouteImport.update({
  id: '/drive',
  path: '/drive',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/_chat',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HomeRoute,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatRoute,
} as any)
const SettingsStorageRoute = SettingsStorageRouteImport.update({
  id: '/storage',
  path: '/storage',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsSourceControlRoute = SettingsSourceControlRouteImport.update({
  id: '/source-control',
  path: '/source-control',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsSnapShotRoute = SettingsSnapShotRouteImport.update({
  id: '/snap-shot',
  path: '/snap-shot',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsScheduledTasksRoute = SettingsScheduledTasksRouteImport.update({
  id: '/scheduled-tasks',
  path: '/scheduled-tasks',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsProvidersRoute = SettingsProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsProjectsRoute = SettingsProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsProjectGroupsRoute = SettingsProjectGroupsRouteImport.update({
  id: '/project-groups',
  path: '/project-groups',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsOpenSourceLicensesRoute =
  SettingsOpenSourceLicensesRouteImport.update({
    id: '/open-source-licenses',
    path: '/open-source-licenses',
    getParentRoute: () => SettingsRoute,
  } as any)
const SettingsKeybindingsRoute = SettingsKeybindingsRouteImport.update({
  id: '/keybindings',
  path: '/keybindings',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsIntegrationsRoute = SettingsIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsGeneralRoute = SettingsGeneralRouteImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsExtensionsRoute = SettingsExtensionsRouteImport.update({
  id: '/extensions',
  path: '/extensions',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsDiagnosticsRoute = SettingsDiagnosticsRouteImport.update({
  id: '/diagnostics',
  path: '/diagnostics',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsConnectionsRoute = SettingsConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsCodeIntelligenceRoute =
  SettingsCodeIntelligenceRouteImport.update({
    id: '/code-intelligence',
    path: '/code-intelligence',
    getParentRoute: () => SettingsRoute,
  } as any)
const SettingsArchivedRoute = SettingsArchivedRouteImport.update({
  id: '/archived',
  path: '/archived',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAppearanceRoute = SettingsAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => SettingsRoute,
} as any)
const ProjectsProjectKeyRoute = ProjectsProjectKeyRouteImport.update({
  id: '/projects/$projectKey',
  path: '/projects/$projectKey',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeNeedsYouRoute = HomeNeedsYouRouteImport.update({
  id: '/needs-you',
  path: '/needs-you',
  getParentRoute: () => HomeRoute,
} as any)
const HomeAgentsRoute = HomeAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => HomeRoute,
} as any)
const AccountSignOutRoute = AccountSignOutRouteImport.update({
  id: '/account/sign-out',
  path: '/account/sign-out',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountCallbackRoute = AccountCallbackRouteImport.update({
  id: '/account/callback',
  path: '/account/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatPullRequestsRoute = ChatPullRequestsRouteImport.update({
  id: '/pull-requests',
  path: '/pull-requests',
  getParentRoute: () => ChatRoute,
} as any)
const HomeViewsViewIdRoute = HomeViewsViewIdRouteImport.update({
  id: '/views/$viewId',
  path: '/views/$viewId',
  getParentRoute: () => HomeRoute,
} as any)
const HomeProjectsProjectIdRoute = HomeProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => HomeRoute,
} as any)
const ChatDraftDraftIdRoute = ChatDraftDraftIdRouteImport.update({
  id: '/draft/$draftId',
  path: '/draft/$draftId',
  getParentRoute: () => ChatRoute,
} as any)
const ChatEnvironmentIdThreadIdRoute =
  ChatEnvironmentIdThreadIdRouteImport.update({
    id: '/$environmentId/$threadId',
    path: '/$environmentId/$threadId',
    getParentRoute: () => ChatRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ChatIndexRoute
  '/calendar': typeof CalendarRoute
  '/connect': typeof ConnectRoute
  '/drive': typeof DriveRoute
  '/home': typeof HomeRouteWithChildren
  '/mail': typeof MailRoute
  '/pair': typeof PairRoute
  '/settings': typeof SettingsRouteWithChildren
  '/usage': typeof UsageRoute
  '/welcome': typeof WelcomeRoute
  '/pull-requests': typeof ChatPullRequestsRoute
  '/account/callback': typeof AccountCallbackRoute
  '/account/sign-out': typeof AccountSignOutRoute
  '/home/agents': typeof HomeAgentsRoute
  '/home/needs-you': typeof HomeNeedsYouRoute
  '/projects/$projectKey': typeof ProjectsProjectKeyRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/archived': typeof SettingsArchivedRoute
  '/settings/code-intelligence': typeof SettingsCodeIntelligenceRoute
  '/settings/connections': typeof SettingsConnectionsRoute
  '/settings/diagnostics': typeof SettingsDiagnosticsRoute
  '/settings/extensions': typeof SettingsExtensionsRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/keybindings': typeof SettingsKeybindingsRoute
  '/settings/open-source-licenses': typeof SettingsOpenSourceLicensesRoute
  '/settings/project-groups': typeof SettingsProjectGroupsRoute
  '/settings/projects': typeof SettingsProjectsRoute
  '/settings/providers': typeof SettingsProvidersRoute
  '/settings/scheduled-tasks': typeof SettingsScheduledTasksRoute
  '/settings/snap-shot': typeof SettingsSnapShotRoute
  '/settings/source-control': typeof SettingsSourceControlRoute
  '/settings/storage': typeof SettingsStorageRoute
  '/home/': typeof HomeIndexRoute
  '/$environmentId/$threadId': typeof ChatEnvironmentIdThreadIdRoute
  '/draft/$draftId': typeof ChatDraftDraftIdRoute
  '/home/projects/$projectId': typeof HomeProjectsProjectIdRoute
  '/home/views/$viewId': typeof HomeViewsViewIdRoute
}
export interface FileRoutesByTo {
  '/calendar': typeof CalendarRoute
  '/connect': typeof ConnectRoute
  '/drive': typeof DriveRoute
  '/mail': typeof MailRoute
  '/pair': typeof PairRoute
  '/settings': typeof SettingsRouteWithChildren
  '/usage': typeof UsageRoute
  '/welcome': typeof WelcomeRoute
  '/pull-requests': typeof ChatPullRequestsRoute
  '/account/callback': typeof AccountCallbackRoute
  '/account/sign-out': typeof AccountSignOutRoute
  '/home/agents': typeof HomeAgentsRoute
  '/home/needs-you': typeof HomeNeedsYouRoute
  '/projects/$projectKey': typeof ProjectsProjectKeyRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/archived': typeof SettingsArchivedRoute
  '/settings/code-intelligence': typeof SettingsCodeIntelligenceRoute
  '/settings/connections': typeof SettingsConnectionsRoute
  '/settings/diagnostics': typeof SettingsDiagnosticsRoute
  '/settings/extensions': typeof SettingsExtensionsRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/keybindings': typeof SettingsKeybindingsRoute
  '/settings/open-source-licenses': typeof SettingsOpenSourceLicensesRoute
  '/settings/project-groups': typeof SettingsProjectGroupsRoute
  '/settings/projects': typeof SettingsProjectsRoute
  '/settings/providers': typeof SettingsProvidersRoute
  '/settings/scheduled-tasks': typeof SettingsScheduledTasksRoute
  '/settings/snap-shot': typeof SettingsSnapShotRoute
  '/settings/source-control': typeof SettingsSourceControlRoute
  '/settings/storage': typeof SettingsStorageRoute
  '/': typeof ChatIndexRoute
  '/home': typeof HomeIndexRoute
  '/$environmentId/$threadId': typeof ChatEnvironmentIdThreadIdRoute
  '/draft/$draftId': typeof ChatDraftDraftIdRoute
  '/home/projects/$projectId': typeof HomeProjectsProjectIdRoute
  '/home/views/$viewId': typeof HomeViewsViewIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_chat': typeof ChatRouteWithChildren
  '/calendar': typeof CalendarRoute
  '/connect': typeof ConnectRoute
  '/drive': typeof DriveRoute
  '/home': typeof HomeRouteWithChildren
  '/mail': typeof MailRoute
  '/pair': typeof PairRoute
  '/settings': typeof SettingsRouteWithChildren
  '/usage': typeof UsageRoute
  '/welcome': typeof WelcomeRoute
  '/_chat/pull-requests': typeof ChatPullRequestsRoute
  '/account/callback': typeof AccountCallbackRoute
  '/account/sign-out': typeof AccountSignOutRoute
  '/home/agents': typeof HomeAgentsRoute
  '/home/needs-you': typeof HomeNeedsYouRoute
  '/projects/$projectKey': typeof ProjectsProjectKeyRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/archived': typeof SettingsArchivedRoute
  '/settings/code-intelligence': typeof SettingsCodeIntelligenceRoute
  '/settings/connections': typeof SettingsConnectionsRoute
  '/settings/diagnostics': typeof SettingsDiagnosticsRoute
  '/settings/extensions': typeof SettingsExtensionsRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/keybindings': typeof SettingsKeybindingsRoute
  '/settings/open-source-licenses': typeof SettingsOpenSourceLicensesRoute
  '/settings/project-groups': typeof SettingsProjectGroupsRoute
  '/settings/projects': typeof SettingsProjectsRoute
  '/settings/providers': typeof SettingsProvidersRoute
  '/settings/scheduled-tasks': typeof SettingsScheduledTasksRoute
  '/settings/snap-shot': typeof SettingsSnapShotRoute
  '/settings/source-control': typeof SettingsSourceControlRoute
  '/settings/storage': typeof SettingsStorageRoute
  '/_chat/': typeof ChatIndexRoute
  '/home/': typeof HomeIndexRoute
  '/_chat/$environmentId/$threadId': typeof ChatEnvironmentIdThreadIdRoute
  '/_chat/draft/$draftId': typeof ChatDraftDraftIdRoute
  '/home/projects/$projectId': typeof HomeProjectsProjectIdRoute
  '/home/views/$viewId': typeof HomeViewsViewIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar'
    | '/connect'
    | '/drive'
    | '/home'
    | '/mail'
    | '/pair'
    | '/settings'
    | '/usage'
    | '/welcome'
    | '/pull-requests'
    | '/account/callback'
    | '/account/sign-out'
    | '/home/agents'
    | '/home/needs-you'
    | '/projects/$projectKey'
    | '/settings/appearance'
    | '/settings/archived'
    | '/settings/code-intelligence'
    | '/settings/connections'
    | '/settings/diagnostics'
    | '/settings/extensions'
    | '/settings/general'
    | '/settings/integrations'
    | '/settings/keybindings'
    | '/settings/open-source-licenses'
    | '/settings/project-groups'
    | '/settings/projects'
    | '/settings/providers'
    | '/settings/scheduled-tasks'
    | '/settings/snap-shot'
    | '/settings/source-control'
    | '/settings/storage'
    | '/home/'
    | '/$environmentId/$threadId'
    | '/draft/$draftId'
    | '/home/projects/$projectId'
    | '/home/views/$viewId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/calendar'
    | '/connect'
    | '/drive'
    | '/mail'
    | '/pair'
    | '/settings'
    | '/usage'
    | '/welcome'
    | '/pull-requests'
    | '/account/callback'
    | '/account/sign-out'
    | '/home/agents'
    | '/home/needs-you'
    | '/projects/$projectKey'
    | '/settings/appearance'
    | '/settings/archived'
    | '/settings/code-intelligence'
    | '/settings/connections'
    | '/settings/diagnostics'
    | '/settings/extensions'
    | '/settings/general'
    | '/settings/integrations'
    | '/settings/keybindings'
    | '/settings/open-source-licenses'
    | '/settings/project-groups'
    | '/settings/projects'
    | '/settings/providers'
    | '/settings/scheduled-tasks'
    | '/settings/snap-shot'
    | '/settings/source-control'
    | '/settings/storage'
    | '/'
    | '/home'
    | '/$environmentId/$threadId'
    | '/draft/$draftId'
    | '/home/projects/$projectId'
    | '/home/views/$viewId'
  id:
    | '__root__'
    | '/_chat'
    | '/calendar'
    | '/connect'
    | '/drive'
    | '/home'
    | '/mail'
    | '/pair'
    | '/settings'
    | '/usage'
    | '/welcome'
    | '/_chat/pull-requests'
    | '/account/callback'
    | '/account/sign-out'
    | '/home/agents'
    | '/home/needs-you'
    | '/projects/$projectKey'
    | '/settings/appearance'
    | '/settings/archived'
    | '/settings/code-intelligence'
    | '/settings/connections'
    | '/settings/diagnostics'
    | '/settings/extensions'
    | '/settings/general'
    | '/settings/integrations'
    | '/settings/keybindings'
    | '/settings/open-source-licenses'
    | '/settings/project-groups'
    | '/settings/projects'
    | '/settings/providers'
    | '/settings/scheduled-tasks'
    | '/settings/snap-shot'
    | '/settings/source-control'
    | '/settings/storage'
    | '/_chat/'
    | '/home/'
    | '/_chat/$environmentId/$threadId'
    | '/_chat/draft/$draftId'
    | '/home/projects/$projectId'
    | '/home/views/$viewId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ChatRoute: typeof ChatRouteWithChildren
  CalendarRoute: typeof CalendarRoute
  ConnectRoute: typeof ConnectRoute
  DriveRoute: typeof DriveRoute
  HomeRoute: typeof HomeRouteWithChildren
  MailRoute: typeof MailRoute
  PairRoute: typeof PairRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  UsageRoute: typeof UsageRoute
  WelcomeRoute: typeof WelcomeRoute
  AccountCallbackRoute: typeof AccountCallbackRoute
  AccountSignOutRoute: typeof AccountSignOutRoute
  ProjectsProjectKeyRoute: typeof ProjectsProjectKeyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usage': {
      id: '/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof UsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pair': {
      id: '/pair'
      path: '/pair'
      fullPath: '/pair'
      preLoaderRoute: typeof PairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mail': {
      id: '/mail'
      path: '/mail'
      fullPath: '/mail'
      preLoaderRoute: typeof MailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drive': {
      id: '/drive'
      path: '/drive'
      fullPath: '/drive'
      preLoaderRoute: typeof DriveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat': {
      id: '/_chat'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/': {
      id: '/home/'
      path: '/'
      fullPath: '/home/'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof HomeRoute
    }
    '/_chat/': {
      id: '/_chat/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof ChatRoute
    }
    '/settings/storage': {
      id: '/settings/storage'
      path: '/storage'
      fullPath: '/settings/storage'
      preLoaderRoute: typeof SettingsStorageRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/source-control': {
      id: '/settings/source-control'
      path: '/source-control'
      fullPath: '/settings/source-control'
      preLoaderRoute: typeof SettingsSourceControlRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/snap-shot': {
      id: '/settings/snap-shot'
      path: '/snap-shot'
      fullPath: '/settings/snap-shot'
      preLoaderRoute: typeof SettingsSnapShotRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/scheduled-tasks': {
      id: '/settings/scheduled-tasks'
      path: '/scheduled-tasks'
      fullPath: '/settings/scheduled-tasks'
      preLoaderRoute: typeof SettingsScheduledTasksRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/providers': {
      id: '/settings/providers'
      path: '/providers'
      fullPath: '/settings/providers'
      preLoaderRoute: typeof SettingsProvidersRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/projects': {
      id: '/settings/projects'
      path: '/projects'
      fullPath: '/settings/projects'
      preLoaderRoute: typeof SettingsProjectsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/project-groups': {
      id: '/settings/project-groups'
      path: '/project-groups'
      fullPath: '/settings/project-groups'
      preLoaderRoute: typeof SettingsProjectGroupsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/open-source-licenses': {
      id: '/settings/open-source-licenses'
      path: '/open-source-licenses'
      fullPath: '/settings/open-source-licenses'
      preLoaderRoute: typeof SettingsOpenSourceLicensesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/keybindings': {
      id: '/settings/keybindings'
      path: '/keybindings'
      fullPath: '/settings/keybindings'
      preLoaderRoute: typeof SettingsKeybindingsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/integrations': {
      id: '/settings/integrations'
      path: '/integrations'
      fullPath: '/settings/integrations'
      preLoaderRoute: typeof SettingsIntegrationsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/general': {
      id: '/settings/general'
      path: '/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof SettingsGeneralRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/extensions': {
      id: '/settings/extensions'
      path: '/extensions'
      fullPath: '/settings/extensions'
      preLoaderRoute: typeof SettingsExtensionsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/diagnostics': {
      id: '/settings/diagnostics'
      path: '/diagnostics'
      fullPath: '/settings/diagnostics'
      preLoaderRoute: typeof SettingsDiagnosticsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/connections': {
      id: '/settings/connections'
      path: '/connections'
      fullPath: '/settings/connections'
      preLoaderRoute: typeof SettingsConnectionsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/code-intelligence': {
      id: '/settings/code-intelligence'
      path: '/code-intelligence'
      fullPath: '/settings/code-intelligence'
      preLoaderRoute: typeof SettingsCodeIntelligenceRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/archived': {
      id: '/settings/archived'
      path: '/archived'
      fullPath: '/settings/archived'
      preLoaderRoute: typeof SettingsArchivedRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/appearance': {
      id: '/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof SettingsAppearanceRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/projects/$projectKey': {
      id: '/projects/$projectKey'
      path: '/projects/$projectKey'
      fullPath: '/projects/$projectKey'
      preLoaderRoute: typeof ProjectsProjectKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/needs-you': {
      id: '/home/needs-you'
      path: '/needs-you'
      fullPath: '/home/needs-you'
      preLoaderRoute: typeof HomeNeedsYouRouteImport
      parentRoute: typeof HomeRoute
    }
    '/home/agents': {
      id: '/home/agents'
      path: '/agents'
      fullPath: '/home/agents'
      preLoaderRoute: typeof HomeAgentsRouteImport
      parentRoute: typeof HomeRoute
    }
    '/account/sign-out': {
      id: '/account/sign-out'
      path: '/account/sign-out'
      fullPath: '/account/sign-out'
      preLoaderRoute: typeof AccountSignOutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/callback': {
      id: '/account/callback'
      path: '/account/callback'
      fullPath: '/account/callback'
      preLoaderRoute: typeof AccountCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat/pull-requests': {
      id: '/_chat/pull-requests'
      path: '/pull-requests'
      fullPath: '/pull-requests'
      preLoaderRoute: typeof ChatPullRequestsRouteImport
      parentRoute: typeof ChatRoute
    }
    '/home/views/$viewId': {
      id: '/home/views/$viewId'
      path: '/views/$viewId'
      fullPath: '/home/views/$viewId'
      preLoaderRoute: typeof HomeViewsViewIdRouteImport
      parentRoute: typeof HomeRoute
    }
    '/home/projects/$projectId': {
      id: '/home/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/home/projects/$projectId'
      preLoaderRoute: typeof HomeProjectsProjectIdRouteImport
      parentRoute: typeof HomeRoute
    }
    '/_chat/draft/$draftId': {
      id: '/_chat/draft/$draftId'
      path: '/draft/$draftId'
      fullPath: '/draft/$draftId'
      preLoaderRoute: typeof ChatDraftDraftIdRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/$environmentId/$threadId': {
      id: '/_chat/$environmentId/$threadId'
      path: '/$environmentId/$threadId'
      fullPath: '/$environmentId/$threadId'
      preLoaderRoute: typeof ChatEnvironmentIdThreadIdRouteImport
      parentRoute: typeof ChatRoute
    }
  }
}

interface ChatRouteChildren {
  ChatPullRequestsRoute: typeof ChatPullRequestsRoute
  ChatIndexRoute: typeof ChatIndexRoute
  ChatEnvironmentIdThreadIdRoute: typeof ChatEnvironmentIdThreadIdRoute
  ChatDraftDraftIdRoute: typeof ChatDraftDraftIdRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatPullRequestsRoute: ChatPullRequestsRoute,
  ChatIndexRoute: ChatIndexRoute,
  ChatEnvironmentIdThreadIdRoute: ChatEnvironmentIdThreadIdRoute,
  ChatDraftDraftIdRoute: ChatDraftDraftIdRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

interface HomeRouteChildren {
  HomeAgentsRoute: typeof HomeAgentsRoute
  HomeNeedsYouRoute: typeof HomeNeedsYouRoute
  HomeIndexRoute: typeof HomeIndexRoute
  HomeProjectsProjectIdRoute: typeof HomeProjectsProjectIdRoute
  HomeViewsViewIdRoute: typeof HomeViewsViewIdRoute
}

const HomeRouteChildren: HomeRouteChildren = {
  HomeAgentsRoute: HomeAgentsRoute,
  HomeNeedsYouRoute: HomeNeedsYouRoute,
  HomeIndexRoute: HomeIndexRoute,
  HomeProjectsProjectIdRoute: HomeProjectsProjectIdRoute,
  HomeViewsViewIdRoute: HomeViewsViewIdRoute,
}

const HomeRouteWithChildren = HomeRoute._addFileChildren(HomeRouteChildren)

interface SettingsRouteChildren {
  SettingsAppearanceRoute: typeof SettingsAppearanceRoute
  SettingsArchivedRoute: typeof SettingsArchivedRoute
  SettingsCodeIntelligenceRoute: typeof SettingsCodeIntelligenceRoute
  SettingsConnectionsRoute: typeof SettingsConnectionsRoute
  SettingsDiagnosticsRoute: typeof SettingsDiagnosticsRoute
  SettingsExtensionsRoute: typeof SettingsExtensionsRoute
  SettingsGeneralRoute: typeof SettingsGeneralRoute
  SettingsIntegrationsRoute: typeof SettingsIntegrationsRoute
  SettingsKeybindingsRoute: typeof SettingsKeybindingsRoute
  SettingsOpenSourceLicensesRoute: typeof SettingsOpenSourceLicensesRoute
  SettingsProjectGroupsRoute: typeof SettingsProjectGroupsRoute
  SettingsProjectsRoute: typeof SettingsProjectsRoute
  SettingsProvidersRoute: typeof SettingsProvidersRoute
  SettingsScheduledTasksRoute: typeof SettingsScheduledTasksRoute
  SettingsSnapShotRoute: typeof SettingsSnapShotRoute
  SettingsSourceControlRoute: typeof SettingsSourceControlRoute
  SettingsStorageRoute: typeof SettingsStorageRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAppearanceRoute: SettingsAppearanceRoute,
  SettingsArchivedRoute: SettingsArchivedRoute,
  SettingsCodeIntelligenceRoute: SettingsCodeIntelligenceRoute,
  SettingsConnectionsRoute: SettingsConnectionsRoute,
  SettingsDiagnosticsRoute: SettingsDiagnosticsRoute,
  SettingsExtensionsRoute: SettingsExtensionsRoute,
  SettingsGeneralRoute: SettingsGeneralRoute,
  SettingsIntegrationsRoute: SettingsIntegrationsRoute,
  SettingsKeybindingsRoute: SettingsKeybindingsRoute,
  SettingsOpenSourceLicensesRoute: SettingsOpenSourceLicensesRoute,
  SettingsProjectGroupsRoute: SettingsProjectGroupsRoute,
  SettingsProjectsRoute: SettingsProjectsRoute,
  SettingsProvidersRoute: SettingsProvidersRoute,
  SettingsScheduledTasksRoute: SettingsScheduledTasksRoute,
  SettingsSnapShotRoute: SettingsSnapShotRoute,
  SettingsSourceControlRoute: SettingsSourceControlRoute,
  SettingsStorageRoute: SettingsStorageRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ChatRoute: ChatRouteWithChildren,
  CalendarRoute: CalendarRoute,
  ConnectRoute: ConnectRoute,
  DriveRoute: DriveRoute,
  HomeRoute: HomeRouteWithChildren,
  MailRoute: MailRoute,
  PairRoute: PairRoute,
  SettingsRoute: SettingsRouteWithChildren,
  UsageRoute: UsageRoute,
  WelcomeRoute: WelcomeRoute,
  AccountCallbackRoute: AccountCallbackRoute,
  AccountSignOutRoute: AccountSignOutRoute,
  ProjectsProjectKeyRoute: ProjectsProjectKeyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
