/** Public OAuth identifiers shared by Code's clients, CLI and relay. */
export const OTTER_ACCOUNTS_URL = "https://accounts.otterware.app/v1/auth";
export const OTTER_CODE_RELAY_URL = "https://relay.code.otterware.app";
export const OTTER_CODE_WEB_URL = "https://code.otterware.app";
export const ACCOUNT_OAUTH_SCOPES = ["openid", "profile", "email", "offline_access"] as const;
export const ACCOUNT_CLIENT_IDS = {
  web: "otter-code-web",
  desktop: "otter-code-desktop",
  mobile: "otter-code-mobile",
  cli: "otter-code-cli",
} as const;

export function accountAuthorizationUrl(input: {
  readonly accountsUrl: string;
  readonly clientId: string;
  readonly redirectUri: string;
  readonly resource: string;
  readonly state: string;
  readonly challenge: string;
}): string {
  const url = new URL(`${input.accountsUrl.replace(/\/$/, "")}/oauth2/authorize`);
  url.search = new URLSearchParams({
    client_id: input.clientId,
    redirect_uri: input.redirectUri,
    response_type: "code",
    scope: ACCOUNT_OAUTH_SCOPES.join(" "),
    resource: input.resource,
    state: input.state,
    code_challenge: input.challenge,
    code_challenge_method: "S256",
  }).toString();
  return url.href;
}

/** PKCE values must be generated by the client that will redeem the code. */
export async function createAccountAuthorization(
  crypto: Pick<typeof globalThis.crypto, "getRandomValues" | "subtle">,
) {
  const bytes = crypto.getRandomValues(new Uint8Array(32));
  const verifier = base64Url(bytes);
  const challenge = base64Url(
    new Uint8Array(await crypto.subtle.digest("SHA-256", new TextEncoder().encode(verifier))),
  );
  return { verifier, challenge, state: base64Url(crypto.getRandomValues(new Uint8Array(32))) };
}

function base64Url(bytes: Uint8Array): string {
  return btoa(String.fromCharCode(...bytes))
    .replaceAll("+", "-")
    .replaceAll("/", "_")
    .replace(/=+$/, "");
}

/** The issuer is an HTTPS URL with a fixed API path, without credentials or query parameters. */
export function normalizeAccountsUrl(value: string): string | null {
  try {
    const url = new URL(value.trim());
    if (
      url.protocol !== "https:" ||
      url.username ||
      url.password ||
      url.search ||
      url.hash ||
      url.pathname.replace(/\/$/, "") !== "/v1/auth"
    )
      return null;
    return `${url.origin}/v1/auth`;
  } catch {
    return null;
  }
}
